import { headers } from "next/headers";
import { adsForHost, adsHeadEnabled } from "@/lib/ads";

/**
 * The AdsKeeper preloader, emitted ONCE per page into the served `<head>` —
 * exactly the tag AdsKeeper's dashboard gives you:
 *
 *   <script src="https://jsc.adskeeper.com/site/SITE_ID.js" async></script>
 *
 * A plain `<script async>` rather than `next/script`, deliberately. With
 * `strategy="afterInteractive"` the raw server HTML carried only a
 * `<link rel="preload">`; the real tag was injected into `<body>` after
 * hydration. AdsKeeper documents this script as a `<head>` tag, and verifying
 * the served HTML is how a publisher checks their install — so it belongs where
 * they expect to find it. React hoists an async script rendered here into
 * `<head>`, which `verify-adskeeper.mjs` asserts against the raw response
 * rather than the hydrated DOM.
 *
 * `async` keeps it non-blocking: the parser does not wait for it, so this costs
 * nothing at render time.
 *
 * Mounted in the PUBLIC layout, never the root one — /admin must not load ad
 * code. Impressions generated by the site's own operator clicking around the
 * editor are precisely what ad networks class as invalid traffic.
 *
 * Renders nothing while the site id is still a placeholder, so the live site
 * stays clean. Individual ad containers are rendered by <AdSlot>.
 */
export function AdsHead() {
  // Each domain is its own registered AdsKeeper site, so the loader id is
  // resolved from the request host — the wrong loader would serve nothing.
  const { siteId } = adsForHost(headers().get("host"));
  if (!adsHeadEnabled(siteId)) return null;
  // eslint-disable-next-line @next/next/no-sync-scripts
  return <script src={`https://jsc.adskeeper.com/site/${siteId}.js`} async />;
}
