import Script from "next/script";

/**
 * Adsterra Social Bar.
 *
 * A self-displaying format: the single loader script positions and triggers
 * itself according to the unit's settings in the Adsterra dashboard, so there
 * is no container element to place. Mounting it once site-wide is the whole
 * integration.
 *
 * Non-blocking by construction. `afterInteractive` tells Next.js to inject the
 * tag only once the page is interactive, which is the App Router equivalent of
 * the classic "put it right before </body>" advice — the HTML parser never
 * waits on it, so it cannot delay first paint or hydration. `async` keeps it
 * off the parser's critical path in the injected tag as well.
 *
 * Rendered from the PUBLIC layout only, never from /admin: an ad bar floating
 * over the editor would be in the way, and impressions generated by the site's
 * own operator are exactly what ad networks treat as invalid traffic.
 */
const SOCIAL_BAR_SRC =
  "https://pl31425115.profitableratecpmnetwork.com/ea/95/62/ea95623c7a2bdcae9ebffe3adce21038.js";

export function AdsterraSocialBar() {
  return (
    <Script
      id="adsterra-social-bar"
      src={SOCIAL_BAR_SRC}
      strategy="afterInteractive"
      async
    />
  );
}
